server:
  port: 8081
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bishe
    username: root
    password: root
    initial-size: 10
    max-active: 100
    min-idle: 2
    validation-query: SELECT 1
    test-on-borrow: true
    test-while-idle: true
mybatis:
  mapperLocations: classpath:mapper/*.xml